services:
  postgres:
    image: postgres:15
    container_name: restaurant_database
    restart: always
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant123
      POSTGRES_DB: restaurant_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U restaurant -d restaurant_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:4000"
    env_file:
      -  ./backend/.env
      - ./backend/proxy.env
    environment:
      - DATABASE_URL=postgresql://restaurant:restaurant123@postgres:5432/restaurant_db
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "bunx prisma migrate dev --name init && bun run start"

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
      args:
        API_URL: ${API_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    env_file:
        - ./frontend/proxy.env

volumes:
  postgres_data: